-- Import des rayons et sous-rayons depuis rayonnage.xlsx
-- Idempotent : rejouable sans creer de doublons (ON CONFLICT sur slug).
-- La ligne 'PROMOTIONS' du fichier source a ete exclue : ce n'est pas un rayon
-- produit mais une section de mise en avant des promotions en cours.

BEGIN;

-- 1. Rayons
INSERT INTO rayons (id, nom, slug, "isActive", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'Produits locaux', 'produits-locaux', true, now(), now()),
  (gen_random_uuid(), 'Épicerie sucrée', 'epicerie-sucree', true, now(), now()),
  (gen_random_uuid(), 'Cafés', 'cafes', true, now(), now()),
  (gen_random_uuid(), 'Épicerie salée', 'epicerie-salee', true, now(), now()),
  (gen_random_uuid(), 'Crémerie et produits laitiers', 'cremerie-et-produits-laitiers', true, now(), now()),
  (gen_random_uuid(), 'Fruits et légumes', 'fruits-et-legumes', true, now(), now()),
  (gen_random_uuid(), 'Viande et poissons', 'viande-et-poissons', true, now(), now()),
  (gen_random_uuid(), 'Charcuterie et traiteur', 'charcuterie-et-traiteur', true, now(), now()),
  (gen_random_uuid(), 'Boissons', 'boissons', true, now(), now()),
  (gen_random_uuid(), 'Bébé', 'bebe', true, now(), now()),
  (gen_random_uuid(), 'Pains et pâtisserie', 'pains-et-patisserie', true, now(), now()),
  (gen_random_uuid(), 'Traiteur', 'traiteur', true, now(), now()),
  (gen_random_uuid(), 'Surgelés', 'surgeles', true, now(), now()),
  (gen_random_uuid(), 'Entretien et nettoyage', 'entretien-et-nettoyage', true, now(), now()),
  (gen_random_uuid(), 'Hygiène et beauté', 'hygienne-et-beaute', true, now(), now()),
  (gen_random_uuid(), 'Mobilier et décoration', 'mobilier-et-decoration', true, now(), now()),
  (gen_random_uuid(), 'Animalerie', 'animalerie', true, now(), now()),
  (gen_random_uuid(), 'Jeux vidéo', 'jeux-video', true, now(), now()),
  (gen_random_uuid(), 'Smartphone et objets connectés', 'smartphone-et-objets-connectes', true, now(), now()),
  (gen_random_uuid(), 'Informatique et bureau', 'informatique-et-bureau', true, now(), now()),
  (gen_random_uuid(), 'Image et son', 'image-et-son', true, now(), now()),
  (gen_random_uuid(), 'Sport', 'sport', true, now(), now()),
  (gen_random_uuid(), 'Mode et textile', 'mode-et-textile', true, now(), now()),
  (gen_random_uuid(), 'Mode et textile de chez nous', 'mode-et-textile-de-chez-nous', true, now(), now())
ON CONFLICT (slug) DO NOTHING;

-- 2. Sous-rayons (rattaches a leur rayon via le slug du parent)
INSERT INTO sous_rayons (id, nom, slug, "rayonId", "isActive", "createdAt", "updatedAt")
SELECT gen_random_uuid(), v.nom, v.slug, r.id, true, now(), now()
FROM (VALUES
  ('produits-locaux', 'Boisson', 'produits-locaux-boisson'),
  ('produits-locaux', 'Gourmandises du pays', 'produits-locaux-gourmandises-du-pays'),
  ('epicerie-sucree', 'Cafés', 'epicerie-sucree-cafes'),
  ('epicerie-sucree', 'Petit déjeuner', 'epicerie-sucree-petit-dejeuner'),
  ('epicerie-sucree', 'Thés', 'epicerie-sucree-thes'),
  ('epicerie-sucree', 'Infusions et boissons chaudes', 'epicerie-sucree-infusions-et-boissons-chaudes'),
  ('epicerie-sucree', 'Confiserie et chocolat', 'epicerie-sucree-confiserie-et-chocolat'),
  ('epicerie-sucree', 'Biscuits', 'epicerie-sucree-biscuits'),
  ('epicerie-sucree', 'Gâteau', 'epicerie-sucree-gateau'),
  ('epicerie-sucree', 'Compotes', 'epicerie-sucree-compotes'),
  ('epicerie-sucree', 'Fruits au sirop', 'epicerie-sucree-fruits-au-sirop'),
  ('epicerie-sucree', 'Crèmes dessert', 'epicerie-sucree-cremes-dessert'),
  ('epicerie-sucree', 'Sucre', 'epicerie-sucree-sucre'),
  ('epicerie-sucree', 'Farines et aide à la pâtisserie', 'epicerie-sucree-farines-et-aide-a-la-patisserie'),
  ('cafes', 'Dosettes et capsules', 'cafes-dosettes-et-capsules'),
  ('cafes', 'Cafés en grains', 'cafes-cafes-en-grains'),
  ('cafes', 'Cafés moulus', 'cafes-cafes-moulus'),
  ('cafes', 'Cafés concentrés', 'cafes-cafes-concentres'),
  ('cafes', 'Cafés soluble', 'cafes-cafes-soluble'),
  ('cafes', 'Filtre et détartrant', 'cafes-filtre-et-detartrant'),
  ('epicerie-salee', 'Huiles', 'epicerie-salee-huiles'),
  ('epicerie-salee', 'Vinaigres et vinaigrettes', 'epicerie-salee-vinaigres-et-vinaigrettes'),
  ('epicerie-salee', 'Pates', 'epicerie-salee-pates'),
  ('epicerie-salee', 'Suces chaudes', 'epicerie-salee-suces-chaudes'),
  ('epicerie-salee', 'Sauces froides conserves et bocaux', 'epicerie-salee-sauces-froides-conserves-et-bocaux'),
  ('epicerie-salee', 'Riz purée et féculents', 'epicerie-salee-riz-puree-et-feculents'),
  ('epicerie-salee', 'Cornichons et condiments', 'epicerie-salee-cornichons-et-condiments'),
  ('epicerie-salee', 'Sels', 'epicerie-salee-sels'),
  ('epicerie-salee', 'Épices et bouillons', 'epicerie-salee-epices-et-bouillons'),
  ('epicerie-salee', 'Soupes', 'epicerie-salee-soupes'),
  ('cremerie-et-produits-laitiers', 'Yaourts', 'cremerie-et-produits-laitiers-yaourts'),
  ('cremerie-et-produits-laitiers', 'Desserts et compotes', 'cremerie-et-produits-laitiers-desserts-et-compotes'),
  ('cremerie-et-produits-laitiers', 'Œufs', 'cremerie-et-produits-laitiers-ufs'),
  ('fruits-et-legumes', 'Fruits', 'fruits-et-legumes-fruits'),
  ('fruits-et-legumes', 'Légumes', 'fruits-et-legumes-legumes'),
  ('fruits-et-legumes', 'Prêt à consommer', 'fruits-et-legumes-pret-a-consommer'),
  ('fruits-et-legumes', 'Fruits et légumes sec', 'fruits-et-legumes-fruits-et-legumes-sec'),
  ('fruits-et-legumes', 'Graines', 'fruits-et-legumes-graines'),
  ('viande-et-poissons', 'Boucherie', 'viande-et-poissons-boucherie'),
  ('viande-et-poissons', 'Volaille et rôtisserie', 'viande-et-poissons-volaille-et-rotisserie'),
  ('viande-et-poissons', 'Poissonnerie', 'viande-et-poissons-poissonnerie'),
  ('viande-et-poissons', 'Traiteur de la mer', 'viande-et-poissons-traiteur-de-la-mer'),
  ('charcuterie-et-traiteur', 'Charcuterie', 'charcuterie-et-traiteur-charcuterie'),
  ('charcuterie-et-traiteur', 'Entrées et salades', 'charcuterie-et-traiteur-entrees-et-salades'),
  ('charcuterie-et-traiteur', 'Pizza', 'charcuterie-et-traiteur-pizza'),
  ('charcuterie-et-traiteur', 'Plats cuisinés', 'charcuterie-et-traiteur-plats-cuisines'),
  ('boissons', 'Colas', 'boissons-colas'),
  ('boissons', 'Sirop et soda', 'boissons-sirop-et-soda'),
  ('boissons', 'Eaux', 'boissons-eaux'),
  ('boissons', 'Jus de fruits', 'boissons-jus-de-fruits'),
  ('bebe', 'Change et soins', 'bebe-change-et-soins'),
  ('bebe', 'Bain et toilette', 'bebe-bain-et-toilette'),
  ('bebe', 'Vêtements', 'bebe-vetements'),
  ('bebe', 'Promenade', 'bebe-promenade'),
  ('bebe', 'Chambre', 'bebe-chambre'),
  ('bebe', 'Éveil', 'bebe-eveil'),
  ('pains-et-patisserie', 'Gâteaux à partager', 'pains-et-patisserie-gateaux-a-partager'),
  ('pains-et-patisserie', 'Pâtisserie individuelles', 'pains-et-patisserie-patisserie-individuelles'),
  ('pains-et-patisserie', 'Tartes', 'pains-et-patisserie-tartes'),
  ('pains-et-patisserie', 'Macarons et mignardise', 'pains-et-patisserie-macarons-et-mignardise'),
  ('pains-et-patisserie', 'Beignets', 'pains-et-patisserie-beignets'),
  ('pains-et-patisserie', 'Muffins', 'pains-et-patisserie-muffins'),
  ('traiteur', 'Entrée', 'traiteur-entree'),
  ('traiteur', 'Plat', 'traiteur-plat'),
  ('traiteur', 'Dessert', 'traiteur-dessert'),
  ('surgeles', 'Glaces', 'surgeles-glaces'),
  ('surgeles', 'Fruits et légumes', 'surgeles-fruits-et-legumes'),
  ('surgeles', 'Poisson', 'surgeles-poisson'),
  ('surgeles', 'Viande', 'surgeles-viande'),
  ('surgeles', 'Pizza', 'surgeles-pizza'),
  ('surgeles', 'Glaçons', 'surgeles-glacons'),
  ('entretien-et-nettoyage', 'Anti-moustique et insecticides', 'entretien-et-nettoyage-anti-moustique-et-insecticides'),
  ('entretien-et-nettoyage', 'Lessives', 'entretien-et-nettoyage-lessives'),
  ('entretien-et-nettoyage', 'Adoucissants et soin du linge', 'entretien-et-nettoyage-adoucissants-et-soin-du-linge'),
  ('entretien-et-nettoyage', 'Produits nettoyants', 'entretien-et-nettoyage-produits-nettoyants'),
  ('entretien-et-nettoyage', 'Essuie tout', 'entretien-et-nettoyage-essuie-tout'),
  ('entretien-et-nettoyage', 'Papier toilette et mouchoirs', 'entretien-et-nettoyage-papier-toilette-et-mouchoirs'),
  ('entretien-et-nettoyage', 'Désodorisant', 'entretien-et-nettoyage-desodorisant'),
  ('entretien-et-nettoyage', 'Accessoires de ménage', 'entretien-et-nettoyage-accessoires-de-menage'),
  ('hygienne-et-beaute', 'Produits solaires', 'hygienne-et-beaute-produits-solaires'),
  ('hygienne-et-beaute', 'Soins du visage', 'hygienne-et-beaute-soins-du-visage'),
  ('hygienne-et-beaute', 'Soins du corps', 'hygienne-et-beaute-soins-du-corps'),
  ('hygienne-et-beaute', 'Soins des cheveux', 'hygienne-et-beaute-soins-des-cheveux'),
  ('hygienne-et-beaute', 'Hygiène dentaire', 'hygienne-et-beaute-hygiene-dentaire'),
  ('hygienne-et-beaute', 'Hygiène intime', 'hygienne-et-beaute-hygiene-intime'),
  ('hygienne-et-beaute', 'Hommes', 'hygienne-et-beaute-hommes'),
  ('hygienne-et-beaute', 'Maquillage', 'hygienne-et-beaute-maquillage'),
  ('hygienne-et-beaute', 'Enfants premiers soins', 'hygienne-et-beaute-enfants-premiers-soins'),
  ('hygienne-et-beaute', 'Incontinence', 'hygienne-et-beaute-incontinence'),
  ('hygienne-et-beaute', 'Cotons', 'hygienne-et-beaute-cotons'),
  ('mobilier-et-decoration', 'Linge de maison', 'mobilier-et-decoration-linge-de-maison'),
  ('mobilier-et-decoration', 'Literie', 'mobilier-et-decoration-literie'),
  ('mobilier-et-decoration', 'Cuisson et ustensiles de cuisine', 'mobilier-et-decoration-cuisson-et-ustensiles-de-cuisine'),
  ('mobilier-et-decoration', 'Vaisselle et art de la table', 'mobilier-et-decoration-vaisselle-et-art-de-la-table'),
  ('mobilier-et-decoration', 'Mobilier et décoration', 'mobilier-et-decoration-mobilier-et-decoration'),
  ('animalerie', 'Chien', 'animalerie-chien'),
  ('animalerie', 'Chat', 'animalerie-chat'),
  ('animalerie', 'Basse-cours', 'animalerie-basse-cours'),
  ('animalerie', 'Poisson', 'animalerie-poisson'),
  ('jeux-video', 'Consoles', 'jeux-video-consoles'),
  ('jeux-video', 'Jeux', 'jeux-video-jeux'),
  ('jeux-video', 'Accessoires', 'jeux-video-accessoires'),
  ('smartphone-et-objets-connectes', 'Téléphone', 'smartphone-et-objets-connectes-telephone'),
  ('smartphone-et-objets-connectes', 'Montres et bracelets connectés', 'smartphone-et-objets-connectes-montres-et-bracelets-connectes'),
  ('smartphone-et-objets-connectes', 'Carte mémoire', 'smartphone-et-objets-connectes-carte-memoire'),
  ('smartphone-et-objets-connectes', 'Batteries externes', 'smartphone-et-objets-connectes-batteries-externes'),
  ('smartphone-et-objets-connectes', 'Objet connecté', 'smartphone-et-objets-connectes-objet-connecte'),
  ('informatique-et-bureau', 'Ordinateur portables', 'informatique-et-bureau-ordinateur-portables'),
  ('informatique-et-bureau', 'Ordinateurs de bureau', 'informatique-et-bureau-ordinateurs-de-bureau'),
  ('informatique-et-bureau', 'Écran pc', 'informatique-et-bureau-ecran-pc'),
  ('informatique-et-bureau', 'Tablette et iPad', 'informatique-et-bureau-tablette-et-ipad'),
  ('informatique-et-bureau', 'Imprimantes et scanners', 'informatique-et-bureau-imprimantes-et-scanners'),
  ('informatique-et-bureau', 'Cartouches toner et papier pour imprimante', 'informatique-et-bureau-cartouches-toner-et-papier-pour-imprimante'),
  ('informatique-et-bureau', 'Casques', 'informatique-et-bureau-casques'),
  ('informatique-et-bureau', 'Micros et enceintes', 'informatique-et-bureau-micros-et-enceintes'),
  ('informatique-et-bureau', 'Stockage', 'informatique-et-bureau-stockage'),
  ('informatique-et-bureau', 'Souris', 'informatique-et-bureau-souris'),
  ('informatique-et-bureau', 'Clavier et tapis', 'informatique-et-bureau-clavier-et-tapis'),
  ('informatique-et-bureau', 'Accessoires informatique', 'informatique-et-bureau-accessoires-informatique'),
  ('image-et-son', 'Téléviseurs', 'image-et-son-televiseurs'),
  ('image-et-son', 'Barre de son', 'image-et-son-barre-de-son'),
  ('image-et-son', 'Home cinéma casques et écouteurs enceintes Blue touth et radio', 'image-et-son-home-cinema-casques-et-ecouteurs-enceintes-blue-touth-et-radio'),
  ('sport', 'Chaussures', 'sport-chaussures'),
  ('sport', 'Tenue de sport', 'sport-tenue-de-sport'),
  ('mode-et-textile', 'Chaussures', 'mode-et-textile-chaussures'),
  ('mode-et-textile', 'Habillement', 'mode-et-textile-habillement'),
  ('mode-et-textile', 'Montres', 'mode-et-textile-montres'),
  ('mode-et-textile', 'Bijoux', 'mode-et-textile-bijoux'),
  ('mode-et-textile-de-chez-nous', 'Chaussure', 'mode-et-textile-de-chez-nous-chaussure'),
  ('mode-et-textile-de-chez-nous', 'Maroquinerie', 'mode-et-textile-de-chez-nous-maroquinerie'),
  ('mode-et-textile-de-chez-nous', 'Habillement', 'mode-et-textile-de-chez-nous-habillement'),
  ('mode-et-textile-de-chez-nous', 'Bijoux', 'mode-et-textile-de-chez-nous-bijoux')
) AS v(rayon_slug, nom, slug)
JOIN rayons r ON r.slug = v.rayon_slug
ON CONFLICT (slug) DO NOTHING;

COMMIT;
